In [67]:
import numpy as np
from src import config
from src import MyUtil as myUtil
print('done import')

done import


In [68]:
recordNames = config.NAME_OF_RECORD
numRecord = len(recordNames)
recordNameForTest = ['a03', 'a05', 'a15', 'a10', 'a19']
trainRqa, trainLabel, testRqa, testLabel = myUtil.loadAllRqa(recordNameForTest)
print('done load RQA')


record for train:  ['a01', 'a02', 'a04', 'a06', 'a07', 'a08', 'a09', 'a11', 'a12', 'a13', 'a14', 'a16', 'a17', 'a18', 'a20', 'b01', 'b02', 'b03', 'b04', 'b05', 'c01', 'c02', 'c03', 'c04', 'c05', 'c06', 'c07', 'c08', 'c09', 'c10']
record for test:  ['a03', 'a05', 'a15', 'a10', 'a19']
done load RQA


In [69]:
print('trainRqa: ', trainRqa.shape)
# print(trainRqa[-10:])
print('trainLabel: ', trainLabel.shape)
print('testRqa: ', testRqa.shape)
# print(testRqa[-10:])
print('testLabel: ', testLabel.shape)

unique, count = np.unique(trainLabel, return_counts=True)
print('trainLabel unique: ', dict(zip(unique, count)))
unique, count = np.unique(testLabel, return_counts=True)
print('testLabel unique: ', dict(zip(unique, count)))

trainRqa:  (17456, 9)
trainLabel:  (17456,)
testRqa:  (2413, 9)
testLabel:  (2413,)
trainLabel unique:  {0: 11330, 1: 6126}
testLabel unique:  {0: 1250, 1: 1163}


In [70]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth=6)
clf = clf.fit(trainRqa, trainLabel)
print(clf.get_params())
print('done fit')

{'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': 6, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'presort': 'deprecated', 'random_state': None, 'splitter': 'best'}
done fit


In [71]:

from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix, classification_report


pre = clf.predict(testRqa)
accuracy = accuracy_score(testLabel, pre)
unique, count = np.unique(testLabel, return_counts=True)
print('testLabel unique: ', dict(zip(unique, count)))
print("accuracy: %.3f"%accuracy)
print('recall: %.3f'%recall_score(testLabel, pre))
print('percision: %.3f'%precision_score(testLabel, pre))
print('confusion_matrix: \n', confusion_matrix(testLabel, pre))
# print('classification_report: \n', classification_report(testLabel, pre))
print('done Test')

testLabel unique:  {0: 1250, 1: 1163}
accuracy: 0.824
recall: 0.739
percision: 0.877
confusion_matrix: 
 [[1129  121]
 [ 303  860]]
done Test


In [72]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix, classification_report

for recordName in recordNameForTest:
    print(recordName)
    testRqa, testLabel, _ = myUtil.loadRqa(recordName, 'test')

    unique, count = np.unique(testLabel, return_counts=True)
    print('testLabel unique: ', dict(zip(unique, count)))

    pre = clf.predict(testRqa)
    accuracy = accuracy_score(testLabel, pre)
    recall = recall_score(testLabel, pre)
    precision = precision_score(testLabel, pre)
    print("accuracy: {:.3f}, recall: {:.3f}, percision: {:.3f}".format(accuracy, recall, precision))
    print('confusion_matrix: \n', confusion_matrix(testLabel, pre))



# from sklearn.decomposition import PCA
# pca = PCA(n_components=2)
# pca.fit(trainRqa)
# print('done fit')

a03
testLabel unique:  {0: 266, 1: 245}
accuracy: 0.830, recall: 0.816, percision: 0.826
confusion_matrix: 
 [[224  42]
 [ 45 200]]
a05
testLabel unique:  {0: 162, 1: 276}
accuracy: 0.799, recall: 0.721, percision: 0.948
confusion_matrix: 
 [[151  11]
 [ 77 199]]
a15
testLabel unique:  {0: 117, 1: 344}
accuracy: 0.787, recall: 0.767, percision: 0.936
confusion_matrix: 
 [[ 99  18]
 [ 80 264]]
a10
testLabel unique:  {0: 409, 1: 99}
accuracy: 0.837, recall: 0.313, percision: 0.674
confusion_matrix: 
 [[394  15]
 [ 68  31]]
a19
testLabel unique:  {0: 296, 1: 199}
accuracy: 0.863, recall: 0.834, percision: 0.826
confusion_matrix: 
 [[261  35]
 [ 33 166]]


In [73]:
# transform = pca.transform(trainRqa)
# print(transform)
#
# import matplotlib.pyplot as plt
# # print(transform[:, 0])
# plt.scatter(transform[:, 0], transform[: ,1], c=trainLabel, label=trainLabel)
# plt.legend()
# plt.scatter(transform[:, 0], transform[: ,1])
# plt.show()

