In [69]:
import numpy as np
from src import config
from src import MyUtil as myUtil
print('done import')


done import


In [70]:
recordNames = config.NAME_OF_RECORD
numRecord = len(recordNames)
recordNameForTest = ['a03', 'a05', 'a15', 'a10', 'a19']
trainRqa, trainLabel, testRqa, testLabel = myUtil.loadAllRqa(recordNameForTest)
print('done load RQA')


record for train:  ['a01', 'a02', 'a04', 'a06', 'a07', 'a08', 'a09', 'a11', 'a12', 'a13', 'a14', 'a16', 'a17', 'a18', 'a20', 'b01', 'b02', 'b03', 'b04', 'b05', 'c01', 'c02', 'c03', 'c04', 'c05', 'c06', 'c07', 'c08', 'c09', 'c10']
record for test:  ['a03', 'a05', 'a15', 'a10', 'a19']
done load RQA


In [71]:
print('trainRqa: ', trainRqa.shape)
# print(trainRqa[-10:])
print('trainLabel: ', trainLabel.shape)
print('testRqa: ', testRqa.shape)
# print(testRqa[-10:])
print('testLabel: ', testLabel.shape)

unique, count = np.unique(trainLabel, return_counts=True)
print('trainLabel unique: ', dict(zip(unique, count)))
unique, count = np.unique(testLabel, return_counts=True)
print('testLabel unique: ', dict(zip(unique, count)))#%%


trainRqa:  (17456, 9)
trainLabel:  (17456,)
testRqa:  (2413, 9)
testLabel:  (2413,)
trainLabel unique:  {0: 11330, 1: 6126}
testLabel unique:  {0: 1250, 1: 1163}


In [72]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(activation='tanh', hidden_layer_sizes=(60, 100, 2), max_iter=500, alpha=0.0001,
                    solver='sgd', random_state=1, validation_fraction=0.1, early_stopping=True)

print(clf)
clf.fit(trainRqa, trainLabel)
print(clf.get_params())
print('done')

MLPClassifier(activation='tanh', early_stopping=True,
              hidden_layer_sizes=(60, 100, 2), max_iter=500, random_state=1,
              solver='sgd')
{'activation': 'tanh', 'alpha': 0.0001, 'batch_size': 'auto', 'beta_1': 0.9, 'beta_2': 0.999, 'early_stopping': True, 'epsilon': 1e-08, 'hidden_layer_sizes': (60, 100, 2), 'learning_rate': 'constant', 'learning_rate_init': 0.001, 'max_fun': 15000, 'max_iter': 500, 'momentum': 0.9, 'n_iter_no_change': 10, 'nesterovs_momentum': True, 'power_t': 0.5, 'random_state': 1, 'shuffle': True, 'solver': 'sgd', 'tol': 0.0001, 'validation_fraction': 0.1, 'verbose': False, 'warm_start': False}
done


In [73]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix

pre = clf.predict(testRqa)
accuracy = accuracy_score(testLabel, pre)
unique, count = np.unique(testLabel, return_counts=True)
print('testLabel unique: ', dict(zip(unique, count)))
print("accuracy: %.3f"%accuracy)
print('recall: %.3f'%recall_score(testLabel, pre))
print('percision: %.3f'%precision_score(testLabel, pre))
print('confusion_matrix: \n', confusion_matrix(testLabel, pre))
# print('classification_report: \n', classification_report(testLabel, pre))
print('done Test')


testLabel unique:  {0: 1250, 1: 1163}
accuracy: 0.823
recall: 0.709
percision: 0.902
confusion_matrix: 
 [[1160   90]
 [ 338  825]]
done Test


In [74]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix


from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix, classification_report

for recordName in recordNameForTest:
    print(recordName)
    testRqa, testLabel, _ = myUtil.loadRqa(recordName, 'test')

    unique, count = np.unique(testLabel, return_counts=True)
    print('testLabel unique: ', dict(zip(unique, count)))

    pre = clf.predict(testRqa)
    accuracy = accuracy_score(testLabel, pre)
    recall = recall_score(testLabel, pre)
    precision = precision_score(testLabel, pre)
    print("accuracy: {:.3f}, recall: {:.3f}, percision: {:.3f}".format(accuracy, recall, precision))
    print('confusion_matrix: \n', confusion_matrix(testLabel, pre))


a03
testLabel unique:  {0: 266, 1: 245}
accuracy: 0.857, recall: 0.743, percision: 0.948
confusion_matrix: 
 [[256  10]
 [ 63 182]]
a05
testLabel unique:  {0: 162, 1: 276}
accuracy: 0.845, recall: 0.783, percision: 0.964
confusion_matrix: 
 [[154   8]
 [ 60 216]]
a15
testLabel unique:  {0: 117, 1: 344}
accuracy: 0.748, recall: 0.689, percision: 0.963
confusion_matrix: 
 [[108   9]
 [107 237]]
a10
testLabel unique:  {0: 409, 1: 99}
accuracy: 0.791, recall: 0.333, percision: 0.452
confusion_matrix: 
 [[369  40]
 [ 66  33]]
a19
testLabel unique:  {0: 296, 1: 199}
accuracy: 0.869, recall: 0.789, percision: 0.872
confusion_matrix: 
 [[273  23]
 [ 42 157]]


In [75]:
# allRqa = []
# allLabel = []
#
# # for iRecord in range(0, numTrain):
# for iRecord in range(10, numRecord):
#     rqa, label, _ = myUtil.loadRqa(recordNames[iRecord], 'train')
#     allRqa = np.append(trainRqa, rqa, axis=0) if len(trainRqa) > 0 else rqa
#     allLabel = np.append(trainLabel, label, axis=0) if len(trainLabel) > 0 else label
# print('done load')
# X_embedded = np.load('backup.npy', allow_pickle=True)

# from sklearn.manifold import TSNE
# X_embedded = TSNE(n_components=2).fit_transform(allRqa)
# print(X_embedded.shape)
# np.save('backup2.npy', X_embedded)
# print('done transform')



In [76]:
# print(X_embedded)
# import numpy as np
# import matplotlib.pyplot as plt
# # print(transform[:, 0])
#
# # X_embedded = np.load('backup.npy', allow_pickle=True)
# print('1')
# normalX = X_embedded[np.where(allLabel == config.NORMAL_LABEL)]
# print(allLabel)
# normalIndex = np.where(allLabel == config.NORMAL_LABEL)
# print(allLabel[np.where(allLabel == config.NORMAL_LABEL)])
# print('---------------')
# apneaX = X_embedded[np.where(allLabel == config.APNEA_LABEL)]
# apneaIndex = np.where(allLabel == config.APNEA_LABEL)
#
# plt.scatter(normalX[:, 0], normalX[: ,1], color='green')
# plt.scatter(apneaX[:, 0], apneaX[: ,1], color='red')
# plt.show()
