In [4]:
import numpy as np
from src import config
from src import MyUtil as myUtil
print('done import')


done import


In [10]:
recordNames = config.NAME_OF_RECORD
numRecord = len(recordNames)
numTrain = config.NUMBER_OF_TRAIN_RECORD
trainRqa = []
trainLabel = []

# for iRecord in range(0, numTrain):
for iRecord in range(10, numRecord):
    rqa, label, _ = myUtil.loadRqa(recordNames[iRecord], 'train')
    trainRqa = np.append(trainRqa, rqa, axis=0) if len(trainRqa) > 0 else rqa
    trainLabel = np.append(trainLabel, label, axis=0) if len(trainLabel) > 0 else label

testRqa = []
testLabel = []
for iRecord in range(0, 10):
    rqa, label, _ = myUtil.loadRqa(recordNames[iRecord], 'test')
    testRqa = np.append(testRqa, rqa, axis=0) if len(testRqa) > 0 else rqa
    testLabel = np.append(testLabel, label, axis=0) if len(testLabel) > 0 else label
print('done load data')



done load data


In [11]:
print('trainRqa: ', trainRqa.shape)
# print(trainRqa[-10:])
print('trainLabel: ', trainLabel.shape)
print('testRqa: ', testRqa.shape)
# print(testRqa[-10:])
print('testLabel: ', testLabel.shape)

unique, count = np.unique(trainLabel, return_counts=True)
print('trainLabel unique: ', dict(zip(unique, count)))
unique, count = np.unique(testLabel, return_counts=True)
print('testLabel unique: ', dict(zip(unique, count)))

trainRqa:  (15443, 12)
trainLabel:  (15443,)
testRqa:  (4407, 12)
testLabel:  (4407,)
trainLabel unique:  {0: 15443}
testLabel unique:  {0: 1722, 1: 2685}


In [14]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(trainRqa, trainLabel)
print(clf)
print('done fit')

ValueError: The number of classes has to be greater than one; got 1 class

In [5]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix


pre = clf.predict(testRqa)
print('pre: ', pre)
test = accuracy_score(testLabel, pre)
print(test)

print('recall: ', recall_score(testLabel, pre))
print('percision: ', precision_score(testLabel, pre))
print('confusion_matrix: \n', confusion_matrix(testLabel, pre))
print('done Test')

pre:  [0 0 0 ... 0 0 0]
0.8301476976542137
recall:  0.35655737704918034
percision:  0.6932270916334662
confusion_matrix: 
 [[3474  154]
 [ 628  348]]
done Test


In [32]:
# print(sorted(scores.keys()))
# print(scores['test_precision_macro'])
# print(scores['test_recall_macro'])

['fit_time', 'score_time', 'test_precision_macro', 'test_recall_macro']
[0.73815267 0.64366604 0.6896529  0.75553469 0.77045814]
[0.72574823 0.64595491 0.68559036 0.75960583 0.76808654]


In [35]:
from sklearn.metrics import accuracy_score

pre = clf.predict(testRqa)
print('pre: ', pre)
test = accuracy_score(testLabel, pre)
print(test)
print('done Test')

pre:  [0 0 1 ... 0 0 0]
0.8311669344238353
done Test


In [36]:
print(clf.get_params())

{'C': 1.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}
