In [82]:
import numpy as np
from src import config
from src import MyUtil as myUtil
print('done import')


done import


In [83]:
recordNames = config.NAME_OF_RECORD
numRecord = len(recordNames)
recordNameForTest = ['a03', 'a05', 'a15', 'a10', 'a19']
trainRqa, trainLabel, testRqa, testLabel = myUtil.loadAllRqa(recordNameForTest)
print('done load RQA')


record for train:  ['a01', 'a02', 'a04', 'a06', 'a07', 'a08', 'a09', 'a11', 'a12', 'a13', 'a14', 'a16', 'a17', 'a18', 'a20', 'b01', 'b02', 'b03', 'b04', 'b05', 'c01', 'c02', 'c03', 'c04', 'c05', 'c06', 'c07', 'c08', 'c09', 'c10']
record for test:  ['a03', 'a05', 'a15', 'a10', 'a19']
done load RQA


In [84]:
print('trainRqa: ', trainRqa.shape)
# print(trainRqa[-10:])
print('trainLabel: ', trainLabel.shape)
print('testRqa: ', testRqa.shape)
# print(testRqa[-10:])
print('testLabel: ', testLabel.shape)

unique, count = np.unique(trainLabel, return_counts=True)
print('trainLabel unique: ', dict(zip(unique, count)))
unique, count = np.unique(testLabel, return_counts=True)
print('testLabel unique: ', dict(zip(unique, count)))

trainRqa:  (17456, 9)
trainLabel:  (17456,)
testRqa:  (2413, 9)
testLabel:  (2413,)
trainLabel unique:  {0: 11330, 1: 6126}
testLabel unique:  {0: 1250, 1: 1163}


In [85]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(trainRqa, trainLabel)
print(clf.get_params())
# print(clf)
print('done fit')

{'C': 1.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}
done fit


In [86]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix, classification_report


pre = clf.predict(testRqa)
accuracy = accuracy_score(testLabel, pre)
unique, count = np.unique(testLabel, return_counts=True)
print('testLabel unique: ', dict(zip(unique, count)))
print("accuracy: %.3f"%accuracy)
print('recall: %.3f'%recall_score(testLabel, pre))
print('percision: %.3f'%precision_score(testLabel, pre))
print('confusion_matrix: \n', confusion_matrix(testLabel, pre))
# print('classification_report: \n', classification_report(testLabel, pre))
print('done Test')

testLabel unique:  {0: 1250, 1: 1163}
accuracy: 0.844
recall: 0.767
percision: 0.895
confusion_matrix: 
 [[1145  105]
 [ 271  892]]
done Test


In [87]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix, classification_report

for recordName in recordNameForTest:
    print(recordName)
    testRqa, testLabel, _ = myUtil.loadRqa(recordName, 'test')

    unique, count = np.unique(testLabel, return_counts=True)
    print('testLabel unique: ', dict(zip(unique, count)))

    pre = clf.predict(testRqa)
    accuracy = accuracy_score(testLabel, pre)
    recall = recall_score(testLabel, pre)
    precision = precision_score(testLabel, pre)
    print("accuracy: {:.3f}, recall: {:.3f}, percision: {:.3f}".format(accuracy, recall, precision))
    print('confusion_matrix: \n', confusion_matrix(testLabel, pre))


a03
testLabel unique:  {0: 266, 1: 245}
accuracy: 0.863, recall: 0.829, percision: 0.879
confusion_matrix: 
 [[238  28]
 [ 42 203]]
a05
testLabel unique:  {0: 162, 1: 276}
accuracy: 0.831, recall: 0.779, percision: 0.943
confusion_matrix: 
 [[149  13]
 [ 61 215]]
a15
testLabel unique:  {0: 117, 1: 344}
accuracy: 0.790, recall: 0.794, percision: 0.913
confusion_matrix: 
 [[ 91  26]
 [ 71 273]]
a10
testLabel unique:  {0: 409, 1: 99}
accuracy: 0.841, recall: 0.374, percision: 0.661
confusion_matrix: 
 [[390  19]
 [ 62  37]]
a19
testLabel unique:  {0: 296, 1: 199}
accuracy: 0.891, recall: 0.824, percision: 0.896
confusion_matrix: 
 [[277  19]
 [ 35 164]]


In [88]:
from sklearn.metrics import accuracy_score

pre = clf.predict(testRqa)
print('pre: ', pre)
test = accuracy_score(testLabel, pre)
print(test)
print('done Test')

pre:  [1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0
 0 0 0 0 0 0 1 1 1 

In [89]:
print(clf.get_params())

{'C': 1.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}
